ALTER TABLE "attractionsg_bookings"
  DROP COLUMN IF EXISTS "quantityAdults",
  DROP COLUMN IF EXISTS "quantityChildren";

ALTER TABLE "attractionsg_bookings"
  ADD COLUMN IF NOT EXISTS "adultCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "childCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "cart" JSONB,
  ADD COLUMN IF NOT EXISTS "unitPrice" DOUBLE PRECISION,
  ALTER COLUMN "quantity" SET DEFAULT 1;
